{"timestamp": "2024-11-26T18:29:53.489352", "level": "ERROR", "message": "Failed to create property", "module": "admin", "function": "create_property", "line": 224, "thread_id": 126343480993600, "exception": {"type": "NameError", "message": "name 'random' is not defined", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 150, in create_property\n    tax_id = f\"TAX{random.randint(100000, 999999)}\"\n                   ^^^^^^\nNameError: name 'random' is not defined. Did you forget to import 'random'"}}
{"timestamp": "2024-11-26T18:31:26.841740", "level": "ERROR", "message": "Failed to create property", "module": "admin", "function": "create_property", "line": 225, "thread_id": 136264655836992, "exception": {"type": "TypeError", "message": "unsupported format string passed to Undefined.__format__", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 204, in create_property\n    property_row = templates.TemplateResponse(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/starlette/templating.py\", line 113, in TemplateResponse\n    return _TemplateResponse(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/starlette/templating.py\", line 39, in __init__\n    content = template.render(context)\n              ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/environment.py\", line 1301, in render\n    self.environment.handle_exception()\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/environment.py\", line 936, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File \"app/templates/admin/properties/table_row.html\", line 14, in top-level template code\n    {{ \"{:,.0f}\".format(property.square_feet) }} sqft\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: unsupported format string passed to Undefined.__format__"}}
{"timestamp": "2024-11-26T18:37:34.054347", "level": "ERROR", "message": "Failed to create property", "module": "admin", "function": "create_property", "line": 225, "thread_id": 136264655836992, "exception": {"type": "TypeError", "message": "unsupported format string passed to Undefined.__format__", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 204, in create_property\n    property_row = templates.TemplateResponse(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/starlette/templating.py\", line 113, in TemplateResponse\n    return _TemplateResponse(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/starlette/templating.py\", line 39, in __init__\n    content = template.render(context)\n              ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/environment.py\", line 1301, in render\n    self.environment.handle_exception()\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/environment.py\", line 936, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File \"app/templates/admin/properties/table_row.html\", line 14, in top-level template code\n    {{ \"{:,.0f}\".format(property.square_feet) }} sqft\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: unsupported format string passed to Undefined.__format__"}}
{"timestamp": "2024-11-26T18:44:25.453807", "level": "ERROR", "message": "Failed to create property: name 'PropertyStatus' is not defined", "module": "admin", "function": "create_property", "line": 235, "thread_id": 133919540541248, "exception": {"type": "NameError", "message": "name 'PropertyStatus' is not defined", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 159, in create_property\n    status=PropertyStatus(status),\n           ^^^^^^^^^^^^^^\nNameError: name 'PropertyStatus' is not defined. Did you mean: 'property_tax'?"}}
{"timestamp": "2024-11-26T19:52:54.326540", "level": "ERROR", "message": "Failed to delete property 1: name 'text' is not defined", "module": "admin", "function": "delete_property", "line": 471, "thread_id": 137583919757120, "exception": {"type": "NameError", "message": "name 'text' is not defined", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 460, in delete_property\n    text(\"CALL delete_property(:property_id)\"), {\"property_id\": property_id}\n    ^^^^\nNameError: name 'text' is not defined. Did you mean: 'next'?"}}
{"timestamp": "2024-11-26T19:53:56.287157", "level": "ERROR", "message": "Failed to delete property 1: name 'text' is not defined", "module": "admin", "function": "delete_property", "line": 471, "thread_id": 137583919757120, "exception": {"type": "NameError", "message": "name 'text' is not defined", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 460, in delete_property\n    text(\"CALL delete_property(:property_id)\"), {\"property_id\": property_id}\n    ^^^^\nNameError: name 'text' is not defined. Did you mean: 'next'?"}}
{"timestamp": "2024-11-26T19:57:24.822403", "level": "ERROR", "message": "Failed to delete property 1: name 'text' is not defined", "module": "admin", "function": "delete_property", "line": 471, "thread_id": 137583919757120, "exception": {"type": "NameError", "message": "name 'text' is not defined", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 460, in delete_property\n    text(\"CALL delete_property(:property_id)\"), {\"property_id\": property_id}\n    ^^^^\nNameError: name 'text' is not defined. Did you mean: 'next'?"}}
{"timestamp": "2024-11-26T19:58:27.323770", "level": "ERROR", "message": "Failed to delete property 1: (mysql.connector.errors.ProgrammingError) 1305 (42000): PROCEDURE real_estate.delete_property does not exist\n[SQL: CALL delete_property(%(property_id)s)]\n[parameters: {'property_id': 1}]\n(Background on this error at: https://sqlalche.me/e/20/f405)", "module": "admin", "function": "delete_property", "line": 471, "thread_id": 128901907683136, "exception": {"type": "ProgrammingError", "message": "(mysql.connector.errors.ProgrammingError) 1305 (42000): PROCEDURE real_estate.delete_property does not exist\n[SQL: CALL delete_property(%(property_id)s)]\n[parameters: {'property_id': 1}]\n(Background on this error at: https://sqlalche.me/e/20/f405)", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: PROCEDURE real_estate.delete_property does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 1969, in _exec_single_context\n    self.dialect.do_execute(\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py\", line 922, in do_execute\n    cursor.execute(statement, parameters)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 357, in execute\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.ProgrammingError: 1305 (42000): PROCEDURE real_estate.delete_property does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 459, in delete_property\n    db.execute(\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py\", line 2308, in execute\n    return self._execute_internal(\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py\", line 2199, in _execute_internal\n    result = conn.execute(\n             ^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 1416, in execute\n    return meth(\n           ^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py\", line 516, in _execute_on_connection\n    return connection._execute_clauseelement(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 1639, in _execute_clauseelement\n    ret = self._execute_context(\n          ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 1848, in _execute_context\n    return self._exec_single_context(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 1988, in _exec_single_context\n    self._handle_dbapi_exception(\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 2343, in _handle_dbapi_exception\n    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 1969, in _exec_single_context\n    self.dialect.do_execute(\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py\", line 922, in do_execute\n    cursor.execute(statement, parameters)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 357, in execute\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nsqlalchemy.exc.ProgrammingError: (mysql.connector.errors.ProgrammingError) 1305 (42000): PROCEDURE real_estate.delete_property does not exist\n[SQL: CALL delete_property(%(property_id)s)]\n[parameters: {'property_id': 1}]\n(Background on this error at: https://sqlalche.me/e/20/f405)"}}
{"timestamp": "2024-11-26T20:04:25.378870", "level": "ERROR", "message": "Failed to delete property 4: Class 'builtins.NoneType' is not mapped", "module": "admin", "function": "delete_property", "line": 487, "thread_id": 134533482547008, "exception": {"type": "UnmappedInstanceError", "message": "Class 'builtins.NoneType' is not mapped", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py\", line 3494, in delete\n    state = attributes.instance_state(instance)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute '_sa_instance_state'\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 467, in delete_property\n    db.delete(property.residential)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py\", line 3496, in delete\n    raise exc.UnmappedInstanceError(instance) from err\nsqlalchemy.orm.exc.UnmappedInstanceError: Class 'builtins.NoneType' is not mapped"}}
{"timestamp": "2024-11-26T20:04:29.816492", "level": "ERROR", "message": "Failed to delete property 5: Class 'builtins.NoneType' is not mapped", "module": "admin", "function": "delete_property", "line": 487, "thread_id": 134533482547008, "exception": {"type": "UnmappedInstanceError", "message": "Class 'builtins.NoneType' is not mapped", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py\", line 3494, in delete\n    state = attributes.instance_state(instance)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute '_sa_instance_state'\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 467, in delete_property\n    db.delete(property.residential)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py\", line 3496, in delete\n    raise exc.UnmappedInstanceError(instance) from err\nsqlalchemy.orm.exc.UnmappedInstanceError: Class 'builtins.NoneType' is not mapped"}}
{"timestamp": "2024-11-26T20:04:33.950855", "level": "ERROR", "message": "Failed to delete property 5: Class 'builtins.NoneType' is not mapped", "module": "admin", "function": "delete_property", "line": 487, "thread_id": 134533482547008, "exception": {"type": "UnmappedInstanceError", "message": "Class 'builtins.NoneType' is not mapped", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py\", line 3494, in delete\n    state = attributes.instance_state(instance)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute '_sa_instance_state'\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 467, in delete_property\n    db.delete(property.residential)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py\", line 3496, in delete\n    raise exc.UnmappedInstanceError(instance) from err\nsqlalchemy.orm.exc.UnmappedInstanceError: Class 'builtins.NoneType' is not mapped"}}
{"timestamp": "2024-11-26T20:05:09.482208", "level": "ERROR", "message": "Failed to delete property 7: Class 'builtins.NoneType' is not mapped", "module": "admin", "function": "delete_property", "line": 487, "thread_id": 134533482547008, "exception": {"type": "UnmappedInstanceError", "message": "Class 'builtins.NoneType' is not mapped", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py\", line 3494, in delete\n    state = attributes.instance_state(instance)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute '_sa_instance_state'\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 467, in delete_property\n    db.delete(property.residential)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py\", line 3496, in delete\n    raise exc.UnmappedInstanceError(instance) from err\nsqlalchemy.orm.exc.UnmappedInstanceError: Class 'builtins.NoneType' is not mapped"}}
{"timestamp": "2024-11-26T20:05:55.832603", "level": "ERROR", "message": "Failed to delete property 4: name 'Contract' is not defined", "module": "admin", "function": "delete_property", "line": 498, "thread_id": 139920310724416, "exception": {"type": "NameError", "message": "name 'Contract' is not defined", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 485, in delete_property\n    db.query(Contract).filter(Contract.property_id == property_id).delete()\n             ^^^^^^^^\nNameError: name 'Contract' is not defined"}}
