{"timestamp": "2024-11-30T21:06:26.842055", "level": "ERROR", "message": "Error fetching properties: 1305 (42000): PROCEDURE real_estate.get_all_properties_with_details does not exist", "module": "main", "function": "index", "line": 36, "thread_id": 127026495670080, "environment": "development"}
{"timestamp": "2024-11-30T21:06:37.992221", "level": "ERROR", "message": "Error fetching properties: 1305 (42000): PROCEDURE real_estate.get_all_properties_with_details does not exist", "module": "main", "function": "index", "line": 36, "thread_id": 127026495670080, "environment": "development"}
{"timestamp": "2024-11-30T21:27:37.738301", "level": "ERROR", "message": "Failed to create client: 1146 (42S02): Table 'real_estate.Clients' doesn't exist", "module": "admin", "function": "create_client", "line": 103, "thread_id": 134262068442944, "environment": "development", "exception": {"type": "ProgrammingError", "message": "1146 (42S02): Table 'real_estate.Clients' doesn't exist", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: Table 'real_estate.Clients' doesn't exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 88, in create_client\n    execute_procedure(\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 48, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.ProgrammingError: 1146 (42S02): Table 'real_estate.Clients' doesn't exist"}}
{"timestamp": "2024-11-30T21:35:48.365300", "level": "ERROR", "message": "Failed to create client: 'None' has no attribute 'split'", "module": "admin", "function": "create_client", "line": 106, "thread_id": 135772140271424, "environment": "development", "exception": {"type": "UndefinedError", "message": "'None' has no attribute 'split'", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 98, in create_client\n    return templates.TemplateResponse(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/starlette/templating.py\", line 113, in TemplateResponse\n    return _TemplateResponse(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/starlette/templating.py\", line 39, in __init__\n    content = template.render(context)\n              ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/environment.py\", line 1301, in render\n    self.environment.handle_exception()\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/environment.py\", line 936, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File \"app/templates/admin/clients/table_row.html\", line 22, in top-level template code\n    {% for role in client.roles.split(',') if client.roles %}\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/utils.py\", line 83, in from_obj\n    if hasattr(obj, \"jinja_pass_arg\"):\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\njinja2.exceptions.UndefinedError: 'None' has no attribute 'split'"}}
{"timestamp": "2024-11-30T21:35:51.215506", "level": "ERROR", "message": "Failed to create client: 'None' has no attribute 'split'", "module": "admin", "function": "create_client", "line": 106, "thread_id": 135772140271424, "environment": "development", "exception": {"type": "UndefinedError", "message": "'None' has no attribute 'split'", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 98, in create_client\n    return templates.TemplateResponse(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/starlette/templating.py\", line 113, in TemplateResponse\n    return _TemplateResponse(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/starlette/templating.py\", line 39, in __init__\n    content = template.render(context)\n              ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/environment.py\", line 1301, in render\n    self.environment.handle_exception()\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/environment.py\", line 936, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File \"app/templates/admin/clients/table_row.html\", line 22, in top-level template code\n    {% for role in client.roles.split(',') if client.roles %}\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/utils.py\", line 83, in from_obj\n    if hasattr(obj, \"jinja_pass_arg\"):\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\njinja2.exceptions.UndefinedError: 'None' has no attribute 'split'"}}
{"timestamp": "2024-11-30T21:38:06.099784", "level": "ERROR", "message": "Dashboard error: No test named 'contains'.", "module": "admin", "function": "admin_dashboard", "line": 51, "thread_id": 135908475512640, "environment": "development", "exception": {"type": "TemplateRuntimeError", "message": "No test named 'contains'.", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 49, in admin_dashboard\n    return templates.TemplateResponse(\"admin/dashboard.html\", context)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/starlette/templating.py\", line 113, in TemplateResponse\n    return _TemplateResponse(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/starlette/templating.py\", line 39, in __init__\n    content = template.render(context)\n              ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/environment.py\", line 1301, in render\n    self.environment.handle_exception()\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/environment.py\", line 936, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File \"app/templates/admin/dashboard.html\", line 1, in top-level template code\n    {% extends \"admin/admin_base.html\" %}\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"app/templates/admin/admin_base.html\", line 1, in top-level template code\n    {% extends \"base.html\" %}\n  File \"app/templates/base.html\", line 26, in top-level template code\n    {% block content %}{% endblock %}\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"app/templates/admin/dashboard.html\", line 23, in block 'content'\n    </div>{% include \"admin/clients/table.html\" %}\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"app/templates/admin/clients/table.html\", line 10, in top-level template code\n    {{ clients|selectattr('roles', 'contains', 'SELLER')|list|length }}\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/async_utils.py\", line 45, in wrapper\n    return normal_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/filters.py\", line 1324, in sync_do_list\n    return list(value)\n           ^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/filters.py\", line 1765, in select_or_reject\n    if func(item):\n       ^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/filters.py\", line 1750, in <lambda>\n    return lambda item: modfunc(func(transfunc(item)))\n                                ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/filters.py\", line 1745, in func\n    return context.environment.call_test(name, item, args, kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/environment.py\", line 589, in call_test\n    return self._filter_test_common(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/environment.py\", line 521, in _filter_test_common\n    raise TemplateRuntimeError(msg)\njinja2.exceptions.TemplateRuntimeError: No test named 'contains'."}}
{"timestamp": "2024-11-30T21:38:06.925393", "level": "ERROR", "message": "Dashboard error: No test named 'contains'.", "module": "admin", "function": "admin_dashboard", "line": 51, "thread_id": 135908475512640, "environment": "development", "exception": {"type": "TemplateRuntimeError", "message": "No test named 'contains'.", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 49, in admin_dashboard\n    return templates.TemplateResponse(\"admin/dashboard.html\", context)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/starlette/templating.py\", line 113, in TemplateResponse\n    return _TemplateResponse(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/starlette/templating.py\", line 39, in __init__\n    content = template.render(context)\n              ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/environment.py\", line 1301, in render\n    self.environment.handle_exception()\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/environment.py\", line 936, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File \"app/templates/admin/dashboard.html\", line 1, in top-level template code\n    {% extends \"admin/admin_base.html\" %}\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"app/templates/admin/admin_base.html\", line 1, in top-level template code\n    {% extends \"base.html\" %}\n  File \"app/templates/base.html\", line 26, in top-level template code\n    {% block content %}{% endblock %}\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"app/templates/admin/dashboard.html\", line 23, in block 'content'\n    </div>{% include \"admin/clients/table.html\" %}\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"app/templates/admin/clients/table.html\", line 10, in top-level template code\n    {{ clients|selectattr('roles', 'contains', 'SELLER')|list|length }}\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/async_utils.py\", line 45, in wrapper\n    return normal_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/filters.py\", line 1324, in sync_do_list\n    return list(value)\n           ^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/filters.py\", line 1765, in select_or_reject\n    if func(item):\n       ^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/filters.py\", line 1750, in <lambda>\n    return lambda item: modfunc(func(transfunc(item)))\n                                ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/filters.py\", line 1745, in func\n    return context.environment.call_test(name, item, args, kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/environment.py\", line 589, in call_test\n    return self._filter_test_common(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/environment.py\", line 521, in _filter_test_common\n    raise TemplateRuntimeError(msg)\njinja2.exceptions.TemplateRuntimeError: No test named 'contains'."}}
{"timestamp": "2024-11-30T21:38:08.231568", "level": "ERROR", "message": "Dashboard error: No test named 'contains'.", "module": "admin", "function": "admin_dashboard", "line": 51, "thread_id": 135908475512640, "environment": "development", "exception": {"type": "TemplateRuntimeError", "message": "No test named 'contains'.", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 49, in admin_dashboard\n    return templates.TemplateResponse(\"admin/dashboard.html\", context)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/starlette/templating.py\", line 113, in TemplateResponse\n    return _TemplateResponse(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/starlette/templating.py\", line 39, in __init__\n    content = template.render(context)\n              ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/environment.py\", line 1301, in render\n    self.environment.handle_exception()\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/environment.py\", line 936, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File \"app/templates/admin/dashboard.html\", line 1, in top-level template code\n    {% extends \"admin/admin_base.html\" %}\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"app/templates/admin/admin_base.html\", line 1, in top-level template code\n    {% extends \"base.html\" %}\n  File \"app/templates/base.html\", line 26, in top-level template code\n    {% block content %}{% endblock %}\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"app/templates/admin/dashboard.html\", line 23, in block 'content'\n    </div>{% include \"admin/clients/table.html\" %}\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"app/templates/admin/clients/table.html\", line 10, in top-level template code\n    {{ clients|selectattr('roles', 'contains', 'SELLER')|list|length }}\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/async_utils.py\", line 45, in wrapper\n    return normal_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/filters.py\", line 1324, in sync_do_list\n    return list(value)\n           ^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/filters.py\", line 1765, in select_or_reject\n    if func(item):\n       ^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/filters.py\", line 1750, in <lambda>\n    return lambda item: modfunc(func(transfunc(item)))\n                                ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/filters.py\", line 1745, in func\n    return context.environment.call_test(name, item, args, kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/environment.py\", line 589, in call_test\n    return self._filter_test_common(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/jinja2/environment.py\", line 521, in _filter_test_common\n    raise TemplateRuntimeError(msg)\njinja2.exceptions.TemplateRuntimeError: No test named 'contains'."}}
{"timestamp": "2024-11-30T21:40:05.123767", "level": "ERROR", "message": "Failed to create agent: 1305 (42000): PROCEDURE real_estate.create_agent does not exist", "module": "admin", "function": "create_agent", "line": 284, "thread_id": 135908475512640, "environment": "development", "exception": {"type": "ProgrammingError", "message": "1305 (42000): PROCEDURE real_estate.create_agent does not exist", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: PROCEDURE real_estate.create_agent does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 273, in create_agent\n    execute_procedure(\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 48, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.ProgrammingError: 1305 (42000): PROCEDURE real_estate.create_agent does not exist"}}
{"timestamp": "2024-11-30T21:40:05.767925", "level": "ERROR", "message": "Failed to create agent: 1305 (42000): PROCEDURE real_estate.create_agent does not exist", "module": "admin", "function": "create_agent", "line": 284, "thread_id": 135908475512640, "environment": "development", "exception": {"type": "ProgrammingError", "message": "1305 (42000): PROCEDURE real_estate.create_agent does not exist", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: PROCEDURE real_estate.create_agent does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 273, in create_agent\n    execute_procedure(\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 48, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.ProgrammingError: 1305 (42000): PROCEDURE real_estate.create_agent does not exist"}}
{"timestamp": "2024-11-30T21:40:08.208060", "level": "ERROR", "message": "Failed to create agent: 1305 (42000): PROCEDURE real_estate.create_agent does not exist", "module": "admin", "function": "create_agent", "line": 284, "thread_id": 135908475512640, "environment": "development", "exception": {"type": "ProgrammingError", "message": "1305 (42000): PROCEDURE real_estate.create_agent does not exist", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: PROCEDURE real_estate.create_agent does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 273, in create_agent\n    execute_procedure(\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 48, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.ProgrammingError: 1305 (42000): PROCEDURE real_estate.create_agent does not exist"}}
{"timestamp": "2024-11-30T21:40:08.439732", "level": "ERROR", "message": "Failed to create agent: 1305 (42000): PROCEDURE real_estate.create_agent does not exist", "module": "admin", "function": "create_agent", "line": 284, "thread_id": 135908475512640, "environment": "development", "exception": {"type": "ProgrammingError", "message": "1305 (42000): PROCEDURE real_estate.create_agent does not exist", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: PROCEDURE real_estate.create_agent does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 273, in create_agent\n    execute_procedure(\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 48, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.ProgrammingError: 1305 (42000): PROCEDURE real_estate.create_agent does not exist"}}
{"timestamp": "2024-11-30T21:40:09.309197", "level": "ERROR", "message": "Failed to create agent: 1305 (42000): PROCEDURE real_estate.create_agent does not exist", "module": "admin", "function": "create_agent", "line": 284, "thread_id": 135908475512640, "environment": "development", "exception": {"type": "ProgrammingError", "message": "1305 (42000): PROCEDURE real_estate.create_agent does not exist", "traceback": "Traceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 706, in cmd_query\n    self._cmysql.query(\n_mysql_connector.MySQLInterfaceError: PROCEDURE real_estate.create_agent does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/routes/admin.py\", line 273, in create_agent\n    execute_procedure(\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/app/core/database.py\", line 48, in execute_procedure\n    cursor.callproc(procedure_name, params)\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/cursor_cext.py\", line 566, in callproc\n    result = self._connection.cmd_query(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 97, in wrapper\n    return method(cnx, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/tygilman/School/CS3200/real-estate-htmx-fastapi/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py\", line 714, in cmd_query\n    raise get_mysql_exception(\nmysql.connector.errors.ProgrammingError: 1305 (42000): PROCEDURE real_estate.create_agent does not exist"}}
{"timestamp": "2024-11-30T21:41:39.331867", "level": "ERROR", "message": "Authentication error: 1305 (42000): PROCEDURE real_estate.get_or_create_admin_role does not exist", "module": "security", "function": "get_current_user", "line": 63, "thread_id": 137540181784384, "environment": "development"}
{"timestamp": "2024-11-30T21:41:40.278911", "level": "ERROR", "message": "Authentication error: 1305 (42000): PROCEDURE real_estate.get_or_create_admin_role does not exist", "module": "security", "function": "get_current_user", "line": 63, "thread_id": 137540181784384, "environment": "development"}
{"timestamp": "2024-11-30T21:41:42.759443", "level": "ERROR", "message": "Authentication error: 1305 (42000): PROCEDURE real_estate.get_or_create_admin_role does not exist", "module": "security", "function": "get_current_user", "line": 63, "thread_id": 137540181784384, "environment": "development"}
{"timestamp": "2024-11-30T21:41:43.479220", "level": "ERROR", "message": "Authentication error: 1305 (42000): PROCEDURE real_estate.get_or_create_admin_role does not exist", "module": "security", "function": "get_current_user", "line": 63, "thread_id": 137540181784384, "environment": "development"}
{"timestamp": "2024-11-30T21:42:11.986868", "level": "ERROR", "message": "Authentication error: 1305 (42000): PROCEDURE real_estate.get_or_create_admin_role does not exist", "module": "security", "function": "get_current_user", "line": 63, "thread_id": 134798576637760, "environment": "development"}
{"timestamp": "2024-11-30T21:42:14.591157", "level": "ERROR", "message": "Authentication error: 1305 (42000): PROCEDURE real_estate.get_or_create_admin_role does not exist", "module": "security", "function": "get_current_user", "line": 63, "thread_id": 134798576637760, "environment": "development"}
{"timestamp": "2024-11-30T21:42:15.508061", "level": "ERROR", "message": "Authentication error: 1305 (42000): PROCEDURE real_estate.get_or_create_admin_role does not exist", "module": "security", "function": "get_current_user", "line": 63, "thread_id": 134798576637760, "environment": "development"}
{"timestamp": "2024-11-30T21:43:40.145009", "level": "ERROR", "message": "Authentication error: 1305 (42000): PROCEDURE real_estate.get_or_create_admin_role does not exist", "module": "security", "function": "get_current_user", "line": 63, "thread_id": 136156975662912, "environment": "development"}
{"timestamp": "2024-11-30T21:47:29.283173", "level": "ERROR", "message": "Authentication error: 1305 (42000): PROCEDURE real_estate.get_or_create_admin_role does not exist", "module": "security", "function": "get_current_user", "line": 63, "thread_id": 139465178666816, "environment": "development"}
{"timestamp": "2024-11-30T21:47:31.606985", "level": "ERROR", "message": "Authentication error: 1305 (42000): PROCEDURE real_estate.get_or_create_admin_role does not exist", "module": "security", "function": "get_current_user", "line": 63, "thread_id": 139465178666816, "environment": "development"}
{"timestamp": "2024-11-30T21:49:38.984191", "level": "ERROR", "message": "Authentication error: 1305 (42000): PROCEDURE real_estate.get_or_create_admin_role does not exist", "module": "security", "function": "get_current_user", "line": 63, "thread_id": 129019965007680, "environment": "development"}
{"timestamp": "2024-11-30T21:50:52.522817", "level": "ERROR", "message": "Authentication error: 1305 (42000): PROCEDURE real_estate.get_or_create_admin_role does not exist", "module": "security", "function": "get_current_user", "line": 63, "thread_id": 124979606251328, "environment": "development"}
{"timestamp": "2024-11-30T21:50:55.458953", "level": "ERROR", "message": "Error fetching properties: 1305 (42000): PROCEDURE real_estate.get_all_properties_with_details does not exist", "module": "main", "function": "index", "line": 36, "thread_id": 124979606251328, "environment": "development"}
{"timestamp": "2024-11-30T21:51:18.993693", "level": "ERROR", "message": "Database error during authentication: 1305 (42000): PROCEDURE real_estate.get_or_create_admin_role does not exist", "module": "auth", "function": "authenticate_user", "line": 58, "thread_id": 124979606251328, "environment": "development"}
{"timestamp": "2024-11-30T21:51:39.933741", "level": "ERROR", "message": "Database error during authentication: 1305 (42000): PROCEDURE real_estate.get_or_create_admin_role does not exist", "module": "auth", "function": "authenticate_user", "line": 58, "thread_id": 124979606251328, "environment": "development"}
{"timestamp": "2024-11-30T21:54:16.558615", "level": "ERROR", "message": "Authentication error: 1305 (42000): PROCEDURE real_estate.get_or_create_admin_role does not exist", "module": "security", "function": "get_current_user", "line": 63, "thread_id": 129888780801856, "environment": "development"}
{"timestamp": "2024-11-30T21:54:17.827922", "level": "ERROR", "message": "Authentication error: 1305 (42000): PROCEDURE real_estate.get_or_create_admin_role does not exist", "module": "security", "function": "get_current_user", "line": 63, "thread_id": 129888780801856, "environment": "development"}
